### ISSUE TITLE
tractor is too high when deflating wheels

### ISSUE THREAD

**Issue by reallogger** [RealismusModding/FS17_RM_soilCompaction#3]

**Comment by stijnwop** [comment]
Should be fixed. @reallogger

**Comment by KITT3000** [comment]
@stijnwop I use the version from 3 days ago (so the latest version available here) and from what I see not only is that the error has not been repaired, the tires have broken, do not bend practically at all (in the earlier version it was clearly seen that the air pressure is low). And the tractor still does not react to a change in air pressure (it does not go down, only wheels, but in a smaller range).

PS. Could this be related to the use of the Gearbox mod?

**Comment by stijnwop** [comment]
I am not aware of Gearbox causing any problems.

Mm, well the current version (https://github.com/RealismusModding/FS17_RM_soilCompaction/commit/0d0aab8a9c7b941cf06aa2004dd3d33f0fd40cd8) is only for the non compressor version. So with in cab control.
I assume you used the compressor to inflate your tires.. so there's still a little bug with that according this issue.

I am working on a fix.

PS. In cab results:
![fsscreen_2018_05_28_12_44_42](https://user-images.githubusercontent.com/12030020/40748636-597e152c-6461-11e8-9b25-dca078e1935f.png)

**Comment by KITT3000** [comment]
Exactly, I use an air compressor, only if the lack of a "flat" is the intended purpose or some mistake (still talking about the air compressor).

**Comment by stijnwop** [comment]
What exactly do you mean by "flak"? The nozzle gun?

**Comment by KITT3000** [comment]
Was supposed to be 'flat' xD

**Comment by stijnwop** [comment]
Oh I see, yeah with the fix the compressor will show the same results as the in cab options does. Like shown on the picture.

Will push a fix according that soon. It was known at least.

**Comment by KITT3000** [comment]
Ok, then I am waiting for a quick fix.
